# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: "hellogo-teste"

stages:

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'beta1.1'
    - task: CmdLine@2
      inputs:
        script: |
          docker image ls

    - task: Docker@2
      inputs:
        containerRegistry: 'Registry-Docker-Verissimo'
        repository: 'hellogo-pos'
        command: 'push'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: 'beta1.1'
    - task: trivy@1
      displayName: "Run trivy scan"
      inputs:
        version: 'latest'
        docker: false
        image: 'verissimomoraes1/hellogo-pos:$(Build.BuildId)'
        severities: 'HIGH,CRITICAL'
        exitCode: '1'
        options: --skip-policy-update