# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: $(Build.BuildId)

stages:

- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build and push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: "Login"
      inputs:
        containerRegistry: 'Registry-Docker-Verissimo'
        command: 'login'
    - task: Docker@2
      displayName: Build and Push a image
      inputs:
        containerRegistry: 'Registry-Docker-Verissimo'
        repository: 'verissimomoraes1/hellogo-pos'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
    - task: CmdLine@2
      inputs:
        script: |
          docker image ls

    - task: trivy@1
      displayName: "Run trivy scan"
      inputs:
        version: 'latest'
        docker: false
        image: 'verissimomoraes1/hellogo-pos:$(Build.BuildId)'
        severities: 'HIGH,CRITICAL'
        exitCode: '0'
        options: --skip-policy-update